[package]
name = "popsim"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive", "wrap_help"] }
emulator_6502 = { version = "1.1.0", features = ["binary_coded_decimal"] }
